version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.1.3

jobs:
    build:
        working_directory: ~/testmonitor/eloquent-incrementable

        docker:
            - image: cimg/php:8.0-node

        steps:
            - run:
                  name: Update Composer
                  command: sudo composer self-update

            - checkout

            - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
            - run: sudo docker-php-ext-install zip
            - run: sudo docker-php-ext-install pdo_sqlite
            - run: sudo docker-php-ext-enable pdo_sqlite

            - restore_cache:
                  keys:
                      - composer-v1-{{ checksum "composer.lock" }}
                      - composer-v1-
            - run:
                  name: Install Composer Dependencies
                  command: composer install -n --ignore-platform-reqs
            - save_cache:
                  key: composer-v1-{{ checksum "composer.lock" }}
                  paths:
                      - vendor

            - run:
                  name: PHP CS Fixer
                  command: vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
            - run:
                  name: PHPCS
                  command: |
                      mkdir -p ./logs/phpcs
                      vendor/bin/phpcs --standard="PSR1,PSR2" -v --report=junit --report-file=logs/phpcs/junit.xml src/
            - run:
                  name: Run Unit Tests
                  command: |
                      mkdir -p ./logs/phpunit
                      vendor/bin/phpunit -d memory_limit=128M --log-junit logs/phpunit/junit.xml --testdox-html logs/phpunit/testdox.html

            - store_artifacts:
                  path: ./logs/phpcs
                  destination: phpcs

            - store_artifacts:
                  path: ./logs/phpunit
                  destination: phpunit
